### ISSUE TITLE
Enable preview for reference docs

### ISSUE THREAD

**Issue by JimDaly** [Microsoft/vscode-docs-authoring#83]
We use the xref syntax to link in reference docs. For example: <xref:Microsoft.Xrm.Sdk.Metadata.EntityMetadata.IsOneNoteIntegrationEnabled>
In the preview, there is nothing but white space where this is used. 
Would be fine if the preview included just the raw text as a short term solution. It would be better than white space. 
Long term, of course it would be best to display the links as they will appear in the docs.

**Comment by qinezh** [comment]
Thanks @JimDaly, it's truly a problem. We'll investigate the solution and update you here.

**Comment by JimDaly** [comment]
@qinezh I would call this a bug rather than an enhancement.

**Comment by qinezh** [comment]
@JimDaly For the long term solution, it would be more like a feature request, as we need to integrate with xref service, which is not in our previous scope for docs-preview.

What do you think about it?

**Comment by JimDaly** [comment]
The fact that blank space is being displayed when an xref is a valid item to include in a topic is a bug. Mitigation strategy s/b to show the raw xref.

Agree that integrating a an actual preview of the xref could be a feature request. But I'd be happy to see the bug fixed in the short term rather than wait for the long term ideal solution. It is confusing to see all the xref only as empty spaces. This damages the experience. I'd be happy to see the <xref > tag content in the preview as a placeholder if that can be achieved faster.

**Comment by meganbradley** [comment]
Thanks @JimDaly 
I agree the short term fix is much better than a blank!
Created this feature: https://ceapex.visualstudio.com/Engineering/_workitems/edit/28713
@qinezh

**Comment by qinezh** [comment]
@jamarw Could you let me know the process to release a new version of docs-preview? I'd like to fix this issue in the new version.

**Comment by mairaw** [comment]
This is still a problem. Can we just do like VS Code preview does and just render the API link as-is? It's better than dropping the text altogether.

**Comment by meganbradley** [comment]
@mairaw 
That is the plan. 

@qinezh @jamarw can we have an update on this?

**Comment by meganbradley** [comment]
@mairaw The user story to track for the as-is rendering is here: 
https://ceapex.visualstudio.com/Engineering/_workitems/edit/29436

**Comment by qinezh** [comment]
Sorry for the late response, new version of docs-preview to support raw xref syntax preview has been released, feel free to have a try. Next step we'll integrate with xref service to render the xref as a link.

**Comment by qinezh** [comment]
Please have a try with latest version of docs-preview, it now can render xref syntax as a link.
